require("transparent").setup({
	-- clear default groups
	groups = {},
	extra_groups = { -- table/string: additional groups that should be cleared
		-- [[ default groups ]]
		"Normal",
		"Comment",
		"Constant",
		"Special",
		"Identifier",
		"Statement",
		"PreProc",
		"Type",
		"Underlined",
		"Todo",
		"String",
		"Function",
		"Conditional",
		"Repeat",
		"Operator",
		"Structure",
		"LineNr",
		"NonText",
		"SignColumn",
		"CursorLineNr",
		"EndOfBuffer",
		"VertSplit",
		-- [[ default groups ]]
		"BqfPreviewFloat",
		"NormalFloat",
		"NormalNC",
		"NvimTreeNormal",
		"NeoTreeNormal",
		"NeoTreeNormalNC",
		"NeoTreePreview",
		"NeoTreeTabInactive",
		"LineNr",
		"CursorColumn",
		-- "CursorLine",
		"CursorLineNr",
		"FloatBorder",
		"WinBar",
		"WinBarNC",
		"TreesitterContext",
		"DapUIPlayPause",
		"DapUIRestart",
		"DapUIStop",
		"DapUIStepOut",
		"DapUIStepBack",
		"DapUIStepInto",
		"DapUIStepOver",
		"DapUIPlayPauseNC",
		"DapUIRestartNC",
		"DapUIStopNC",
		"DapUIStepOutNC",
		"DapUIStepBackNC",
		"DapUIStepIntoNC",
		"DapUIStepOverNC",
		"Folded",
		"SignColumn",
		"StatusLine",
		"TelescopeBorder",
		"TelescopeNormal",
		"TelescopePreviewNormal",
		"TelescopeResultsNormal",
		"TelescopePromptNormal",
		-- "TabLine"
		-- "TabLineSel",
		-- "TabLineFill",
		"TreesitterContextLineNumber",
		"QuickFixLine",
		-- "Pmenu",
		-- "PmenuSel",
		-- "PmenuSbar",
		-- "PmenuThumb",
		"NotifyINFOBody",
		"NotifyWARNBody",
		"NotifyERRORBody",
		"NotifyDEBUGBody",
		"NotifyTRACEBody",
		"NotifyINFOBorder",
		"NotifyWARNBorder",
		"NotifyERRORBorder",
		"NotifyDEBUGBorder",
		"NotifyTRACEBorder",
		"WhichKeyFloat",
	},
})
